### ISSUE TITLE
Don't treat missing mli file as error

### ISSUE THREAD

**Issue by SnarkBoojum** [Karmaki/coq-dpdgraph#103]
I was having a hard time compiling dpdgraph because by default it uses "-w +A", while the current code (1.0+8.15) lacks a few .mli files and it's been a warning in ocaml since some time (I'm using 4.13.1), until I made the following modification:
```
--- coq-dpdgraph.orig/Makefile.in
+++ coq-dpdgraph/Makefile.in
@@ -49,7 +49,7 @@
 OCAMLLEX=@OCAMLLEX@
 OCAMLYACC=@OCAMLYACC@
 
-WARN_ERR := -warn-error +a
+WARN_ERR := -warn-error +a-70
 OCAMLFLAGS :=  -w +a $(WARN_ERR) -g -dtypes $(INCLUDES) -c
 OCAMLFLAGS += $(OCAML_EXTRA_OPTS)
 OCAMLOPTFLAGS = -c
```

**Comment by Karmaki** [comment]
Wouldn't it better to add the missing `.mli` files instead of removing the error message?

**Comment by SnarkBoojum** [comment]
Well, missing a .mli is normally just a warning -- it's Makefile.in which turns it into an error message. Notice I could also have silenced the warning.

Those .mli files can be obtained by running `ocamlc -i` if that makes sense, but since the project hasn't them already, I'm not sure that's what the developers want.

**Comment by ybertot** [comment]
The fact all warnings are treated as errors is already documented in the README.md file (the source is actually in the meta.yml file).  Modulo a small typo in the wording I propose that we make no more effort to document this.

On the other hand, adding the missing mli file is a good fix, which I will perform asap.

**Comment by ybertot** [comment]
See PR #108

**Comment by ybertot** [comment]
Thks @SnarkBoojum
