### ISSUE TITLE
Please pick the version you prefer for Coq 8.17 in Coq Platform 2023.03

### ISSUE THREAD

**Issue by MSoegtropIMC** [Karmaki/coq-dpdgraph#113]
The Coq team released Coq `8.17+rc1` on December 29th, 2022 and plans to release Coq 8.17.0 around March 7th, 2023.
The corresponding Coq Platform release `2023.03` should be released before **April 14th, 2023**.
It can be delayed in case of difficulties until June 30, 2023, but this should be an exception.

This issue is to inform you that the opam package we are currently testing in Coq Platform CI **works fine** with Coq `8.17+rc1`.

Coq Platform CI is currently testing opam package `coq-dpdgraph.1.0+8.16`
from platform patch repository https://github.com/coq/platform/tree/main/opam/opam-coq-archive/released/packages/coq-dpdgraph/coq-dpdgraph.1.0+8.16/opam.  **This means we had to weaken some version restrictions in the opam package, but no other changes were required.**

**In case this is the version you want to see in Coq Platform, there is nothing to do for you - please just close this issue.**

In case you would prefer to see an updated or an older version in the upcoming Coq Platform `2023.03`, please inform us as soon as possible and before **March 21st, 2023**!

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.17~2023.03+preview1`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.17~2023.03+preview1.sh) which already supports Coq version `8.17+rc1` and contains already working (possibly patched / commit pinned) Coq Platform packages.

In case you want to select a different version, please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/335

**Comment by MSoegtropIMC** [comment]
I just updated coq-dpdgraph in Coq Platform to version 1.0+8.17.

@ybertot : please close this issue to confirm that this is the version you want to be used.

**Comment by ybertot** [comment]
In this case, you could have left coq-dpdgraph to version 1.0+8.16, because there is no significant difference between the two revisions.  I prepared version 1.0+8.17 by mistake because I had not read you message carefully enough.

I update the dependency range on coq in the opam file for coq-dpdgraph 1.0+8.16, so it is really possible (but not necessary) to move back to that revision.  I have no opinion about what is best in this case.

I will close this issue, because I think there is no point adding more work on this topic.

**Comment by MSoegtropIMC** [comment]
I agree - let's leave it at this and use 8.17 just for clarity.
