### ISSUE TITLE
Publish a release compatible with Coq 8.20

### ISSUE THREAD

**Issue by SnarkBoojum** [Karmaki/coq-dpdgraph#134]
(I'm trying to update the Coq packages in Debian, so I'm looking for a set of coherent upstream releases)

**Comment by ybertot** [comment]
commit 4fa1b8aaeb7bc4a948327755e436135ac2c9d2b9 on branch coq-v8.20

**Comment by ybertot** [comment]
https://github.com/coq-community/coq-dpdgraph/releases/tag/v1.0%2B8.20

**Comment by ybertot** [comment]
Wait a minute, I made a mistake, and need to redo.

**Comment by ybertot** [comment]
It should be correct now, with commit 0effa4706c9b7f27c3476573bc046664f16cdb0f

**Comment by ybertot** [comment]
It seems everything is correct now.  Please take the commit mentioned above and close the issue if it works well.  You may have to wait on coq-dpdgraph.1.0+8.20 to be available in the released opam repository if this plays a role in you packaging process.

**Comment by SnarkBoojum** [comment]
I use the github-generated tarball, and that one is automatically made when you tag a release.

**Comment by ybertot** [comment]
No problem using the github generated tarball.  We can discuss why we make the effort of generating one ourselves the next time we meet.
