### ISSUE TITLE
coq-dpdgraph fails to build on trusty because of -safe-string

### ISSUE THREAD

**Issue by JasonGross** [Karmaki/coq-dpdgraph#17]
Please remove `-safe-string` or ensure that ocaml supports it before passing it in, or give me a makefile variable that I can set to remove `-safe-string`.  I'm trying to get HoTT to use a newer version of dpdgraph on travis, and [this is currently the issue I'm running into](https://s3.amazonaws.com/archive.travis-ci.org/jobs/217880138/log.txt),

**Comment by Karmaki** [comment]
The `-safe-string` option appeared in ocaml 4.02, and you are using ocaml 4.01.0. Indeed this should be tested in the Makefile. I'll try to fix that soon.

**Comment by Karmaki** [comment]
Hope the problem is fixed. Let me know if it is ok for you now.
