### ISSUE TITLE
Minimal instructions?

### ISSUE THREAD

**Issue by cpitclaudel** [Karmaki/coq-dpdgraph#3]
Hey there,

Would it be possible to add just a few lines to the README with instructions on how to use this tool after installing it from source? I used the standalone version in the past, but I'm not familiar with Coq plugins, so instructions on how to use the new version would be welcome.

(I saw the OPAM version, but I don't use it yet: it doesn't seem to be supported by Coq's dev team, and I haven't invested the time yet to understand how to apply my own patches on top of OPAM sources).

Thanks!

**Comment by Karmaki** [comment]
Can you give more details on which step is not clear enough?
Did you configure, compile, install, try the tests as explained in the README file?

**Comment by ybertot** [comment]
You may also read the contents of the tests directory, which will give an example to follow.

**Comment by cpitclaudel** [comment]
My only concern was this part:

```
./dpdgraph.cmxs : a plugin to be loaded in Coq
```

I was just suggesting that i might be good to give an example of loading a plugin into Coq :)

**Comment by Karmaki** [comment]
In the Makefile, you can see that the tests run with this kind of command:
    
    coqtop -R .. dpdgraph < Test.cmd

You are right: this has to be fixed in the README file. Thanks.

**Comment by cpitclaudel** [comment]
Awesome, thanks!

**Comment by Karmaki** [comment]
Updated README.
