### ISSUE TITLE
Clarify the meaning of branches

### ISSUE THREAD

**Issue by maximedenes** [Karmaki/coq-dpdgraph#50]
Hello,

When I submitted a PR recently, I got confused by the meaning of branches. My bad, of course, but I think it would help external contributors if you could:
- rename `coq-trunk` into `coq-master` (it will make it easier to guess that this is the relevant branch for compatibility patches for Coq)
- clarify the role of `master` vs `coq-8.8` / `coq-master`

Thanks!

**Comment by Karmaki** [comment]
You are right. It seems that many people get confused with that organization. Don't have time to do it right now, but I plan to:

- rename `coq-trunk` into `coq-master`
- remove the useless and confusing `master` branch
- my last question is: which one should be the default branch, the last release (`coq-8.8` at the moment) or `coq-master`?

**Comment by maximedenes** [comment]
Thanks!

> my last question is: which one should be the default branch, the last release (coq-8.8 at the moment) or coq-master?

I think the default  branch should be the one were the actual dpdgraph development takes place (as opposed to patches for compatibility with Coq). Which one it is depends on your merge / backport workflow.
