### ISSUE TITLE
coq-8.9 support

### ISSUE THREAD

**Issue by vzaliva** [Karmaki/coq-dpdgraph#58]
Current version in OPAM is not compatible with latest Coq version 8.9

**Comment by ybertot** [comment]
I am working on it.  For the record, it will be a version using commit 7110697

**Comment by ybertot** [comment]
The coq-dpdgraph part of this is fixed in branch coq-8.9.  The opam part is opam-coq-archive PR#591

**Comment by vzaliva** [comment]
thanks!
