### ISSUE TITLE
installation from source code problem

### ISSUE THREAD

**Issue by LouGlzHuesca** [Karmaki/coq-dpdgraph#62]
I am trying to install this plugin but after following the instructions to install from pre-packaged source archive (situation 3) I get the following:
install: cannot change permissions of ‘/usr/local/lib/coq/user-contrib/dpdgraph/’: No such file or directory
The unpacked files are in my Downloads directory and the Coq version is 8.8 installed (global) via sources using the instructions in the old cocorico wiki page.
Thanks

**Comment by ybertot** [comment]
Maybe you should decompose the second line as such:

`configure && make`

For the `make install` command, you need to perform it with super-user privileges.  I don't know what is your exact setup, often you need to use some `su` or `sudo` command for this.  It should be the same as the one you used to install Coq globally.

**Comment by ybertot** [comment]
Incidentally, it is also possible to use coq-dpdgraph without installiing it globally.

**Comment by LouGlzHuesca** [comment]
Yves, thanks for the suggestions. 
I forgot to say that I was installing the plugin using superuser privileges but it worked by decomposing the line as:
./configure && make
sudo make install 
Maybe it could be useful to update the installation instructions pointing out these suggestions.
Thanks again ^.^
Amitiés
