### ISSUE TITLE
make: *** No rule to make target 'test'.  Stop. 

### ISSUE THREAD

**Issue by georgydunaev** [Karmaki/coq-dpdgraph#8]
How can I solve this issue?
make -s test
make: **\* No rule to make target 'test'.  Stop.
I have a hunch it's not a proper result:)

**Comment by Karmaki** [comment]
Did you clone this git repository? 
If so, did the previous steps run with no error ( `autoconf ; ./configure ; make` )?

**Comment by georgydunaev** [comment]
Previous steps run with no error except "make" step.

$make
....
   * build dpdgraph.cmxs
make -f Make_coq dpdgraph.cmxs
make[1]: Entering directory '/home/user/COQ/dpdgraph/coq-dpdgraph'
make[1]: *** No rule to make target 'dpdgraph.cmxs'.  Stop.
make[1]: Leaving directory '/home/user/COQ/dpdgraph/coq-dpdgraph'
Makefile:61: recipe for target 'dpdgraph.cmxs' failed
make: *** [dpdgraph.cmxs] Error 2

p.s. "make clean" is also gives error2

**Comment by Karmaki** [comment]
I have had similar problems, and it was because `coq` was not installed properly. I fixed it with:
```
$ opam uninstall coq
# a warning told me that this directory was not remove because it was not empty.
# I've had to remove it manually :
$ rm -rf <opam/root/4.03.0/share/coq
$ opam install coq
```
I close this issues since [Travis CI output](https://travis-ci.org/Karmaki/coq-dpdgraph) looks ok.
Fell free to reopen with more details if you wish.
