### ISSUE TITLE
How to prevent opam from installing Coq?

### ISSUE THREAD

**Issue by georgydunaev** [Karmaki/coq-dpdgraph#9]
user@debiansda:~/COQ$ opam install coq-dpdgraph
The following actions will be performed:
- install   camlp5.6.14                           [required by coq]
- install   ocamlgraph.1.8.6                      [required by coq-dpdgraph]
- install   coq.8.5.0                             [required by coq-dpdgraph]
- install   coq-dpdgraph.0.6
  === 4 to install ===
  Do you want to continue ? [Y/n] n

Maybe you know how to point that I already have installed Coq. I want to improve existing system with this plugin.

**Comment by Karmaki** [comment]
I don't think it is possible to mix opam and other installations. If you don't use opam already, I would suggest you to rather clone the git repository and compile it yourself. Notice that you don't have to install `coq-dpdgraph` to use it.
